### ISSUE TITLE
[BUG] Store App won't Install 

### ISSUE THREAD

**Issue by PeterW46** [ShammyLevva/FTAnalyzer#168]
7.7 ?? It is the version in the Microsoft App Store, I am unable to install so I can't tell you the version

The current version works fine (7.6.3.9999).  I am unable to install the new version from the Microsoft App store.

When I try to install I press "Install" and then on the left side I get the message "Error" (See screensnip).  If I press "See details I get the following error Code: 0x803FB005

I am running Windows 10 (see screenshot) - its an Enterprise version (sold without Cortana - which is why I chose to pay more but within the past year an MS update has foisted Cortana on me).  I normally lock out Cortana (using "Shutup10") but even if I enable all the MS crap that seeks to track what I do, it still won't install.

I have donated in the past.  I would be happy to buy it if it contains the wherewithal to produce mapping with Birth, and death locations (I have an Anqet Subscription).  I bought the Progeny Map option for £30 recently but it can't cope with something over 1800 Place locations.

I recognise that when something is free, I am the product.  I would never sign up on Facebook or Linked in and once it became obvious that Google, MS and the like knew my age, sex, interests etc I set about blocking them to the extent its possible.  My default browser is Brave.
![FTAnalyzer Error](https://user-images.githubusercontent.com/64363401/80310108-edc0bc00-87d0-11ea-9d22-78812e799365.png)
![OS system](https://user-images.githubusercontent.com/64363401/80310171-442dfa80-87d1-11ea-8462-51e541e5ab01.PNG)

Thanks for developing it, it's a very good program

Peter Williams

**Comment by ShammyLevva** [comment]
The click once version is scheduled to die, it will soon stop working. If you wish to continue using the program you should uninstall the click once and install the Microsoft store version. There is likely conflicts if you have the old click once version still installed.

The other possibility is that Windows 10 Store files aren’t corrupted (this happens and is usually fixed with a reboot) but sometimes needs to run the troubleshooter to clean up cache files. See https://windowsreport.com/0x803fb005-microsoft-store/

If that fails there is a fallback option to use the github release version www.ftanalyzer.com/releases this tends to run a bit behind the live version and doesn’t update. However it’s an option if the store fails. 

Ps. I took the liberty of editing your report to remove your email address to protect your privacy.

**Comment by PeterW46** [comment]
Alexander

 

Thank you first for expunging my email address.

 

Also for the link to the windowsreport.com.  I have worked my way down this list and even though the image was updated or corrected and scannow found and replaced 3 files I still get the same problem.  I just can’t install from the Store, there is always the same problem.  I notice incidentally that FT Analyzer has disappeared from the Store but the old link still works.

 

I will run the old version until it is no longer available and then try again with the Microsoft Store Version

 

Peter

**Comment by ShammyLevva** [comment]
Hi Peter,

You are better off running the release version from www.ftanalyzer.com/releases this has quite a few bug fixes from the old Click Once version. You “install” by unzipping the download to a folder of your choice and running the FTAnalyzer.exe file.

FTAnalyzer is still in the Windows Store the link is https://www.microsoft.com/store/apps/9PMJL9HVPL7X?cid=storebadge&ocid=badge

**Comment by PeterW46** [comment]
Shammy

 

Thank you for your further advice.  There is no longer a link to make a donation unless I’ve missed it?  I have tried once again this morning to download from the Microsoft App Store but I get the same error message.

 

I have tested it on my wife’s Windows 10 computer and it does install.  The problem lies with my computer.  I have tried the SCANNOW process a second time but it hasn’t made any difference.  I don’t know whether it makes any difference that I am running the Enterprise edition which doesn’t come with X-Box.

 

What is strange is that it allows me to install Adobe Photoshop Express on this computer, so it is not rejecting all free apps.

 

Thank you again

 

Peter Williams

**Comment by ShammyLevva** [comment]
There has never been a donations button there. I have more than sufficient personal funds for my needs so am happy to make the program free as my gift to the genealogy community. I don’t have any ads nor do I collect or use any personal information, so no you aren’t the product either. Indeed as an IT security professional I actively advise against giving away too much personal info. 

For full transparency the windows store does provide me with a count of the number of users and the country they live in as well as any broad demographic data they have entered (age group, gender, etc). However there’s nothing that can identify individuals not even IP address and I’d actively avoid any personal data due to GDPR legislation which I positively support. 

To the problem at hand... When you get the error do you have a screenshot of the contents of the details button report all I’ve seen so far is the error number which simply means there was an unknown error see details for information. So without the details I don’t know more. 

Unfortunately I’m not expecting the “details” to be very detailed. Microsoft have a habit of saying there’s a problem but not saying what it is. It may however give an insight into the issue.

**Comment by PeterW46** [comment]
Alexander

 

Whatever has been done by Microsoft or you has worked.  I can now download and install from the Microsoft Store.  Thank you again for a program of amazing utility.  It is a very important complement to FH.

 

Curiosity lead me to the Aberdeen Harbour website (our eldest son lives in Montreal and works for Fednav, they don’t sail to Aberdeen).  I am also very impressed with the “Vessels in Port” page.

 

Thanks again

 

Peter Williams

**Comment by ShammyLevva** [comment]
User confirmed Issue resolved.
