### ISSUE TITLE
Data exception (Value too large/small for Int64 on load)

### ISSUE THREAD

**Issue by jdrosdahl** [ShammyLevva/FTAnalyzer#59]
On File / Open GEDCOM File:
1. Successfully completed 'Loading Sources' step
2. Successfully completed 'Loading Individuals' step
3. Ran to the end of 'Loading Families' step, and stopped with the following error message:
***
Error: Problem processing your file.  Please try again.
If this problem persists, please report this at:
http://www.ftanalyzer.com/issues.  Error was Value was either too large or too small for an Int64  
***

The exact same GEDCOM file was previously processed to completion, and outputs were exported successfully. I tried running multiple GEDCOM's that had run successfully in the past, and all had the same result.  Tried with a number of options changed, to no avail.  Re-installed FTA, powered desktop down/up, same result.

**Expected behavior**

I expected all steps to complete successfully, and to have output files available for review.

GEDCOM was exported from Ancestry.com.  43,495 people

**Screenshots**
 
![image](https://user-images.githubusercontent.com/45953956/50123830-15843500-0217-11e9-912b-f72ff27d3677.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Mozilla Firefox
 - Version: 64.0 - 64-bit

**Additional context**

**Comment by ShammyLevva** [comment]
Thanks for feedback it looks like it's crashing on loading the relationship calculations. I fixed something for v7.2.0.0 are you able to test that version (it would be a manual install - unzip files to a desktop folder and run the FTAnalyzer.exe file) this would tell me if the fix worked for your tree.

Beta is available [here](https://www.dropbox.com/s/3iau1deysai4deb/FTAnalyzer.v7.2.0.0a.zip?dl=0)

**Comment by jdrosdahl** [comment]
Alexander,
I followed the Beta link and I got a 404 not found.



Sent from Mail for Windows 10

**Comment by ShammyLevva** [comment]
Yes sorry v7.2.0.0 is now out and included what I’m guessing is the fix for this issue. If that fixes it can you close this issue if not can you let me know and I can look again at this.

**Comment by jdrosdahl** [comment]
Alexander,

I downloaded the new version and ran it.

It appeared to run much faster (after I turned on the ‘retry’ option for cr-lf), but it still failed at the same point with the same error.



Sent from Mail for Windows 10

**Comment by ShammyLevva** [comment]
Then there’s not a lot I can do to understand what’s going on without testing it on your file. I have tested well over 100 people’s files and always promise to respect absolute privacy for their file and to delete it once I’ve fixed the issue. 

This is one of those the tree is too large to store the value in a field because the type of field I’m using is ok until it gets to a certain size then it fails. Unfortunately until I can see the result of loading a huge field I’m left guessing where it is crashing. 

Email address is FTAnalyzer@gmail.com

**Comment by jdrosdahl** [comment]
FTA was working a week ago (12/14), then it started crashing on the same GEDCOM file.

On 12/14, I exported all the files and the GEDCOM status to Excel.  Based on those messages, I did clean up.

So, I can send you whatever you prefer:
- GEDCOM file from 12/14/2018
- Excel file including GEDCOM Stats, Individuals, Family, Sources and Facts based on 12/14 GEDCOM file
- GEDCOM file from 12/16/2018 (many errors messages addressed)

Just let me know and I’ll zip it and send it.

Thanks,

Jim

Sent from Mail for Windows 10

**Comment by jdrosdahl** [comment]
I sent a zipped GEDCOM yesterday afternoon.  Will give it another shot.

Sent from Mail for Windows 10

**Comment by jdrosdahl** [comment]
I’ve sent two different e-mails with the GEDCOM attached (8MB).  Let me know if you haven’t received it.

Jim

Sent from Mail for Windows 10

**Comment by ShammyLevva** [comment]
It's maybe because it's a large attachment that it's taking time. Gmail is known for not being great with big attachments.

**Comment by ShammyLevva** [comment]
Nothing received yet. It may be worth zipping up the file first? GEDCOM files do compress very well.

**Comment by ShammyLevva** [comment]
Strange that it's not come through. You could contact me on Private message on Facebook Messenger and send there?

**Comment by jdrosdahl** [comment]
Just got home.  I’ll try the FB Messenger route.

Sent from Mail for Windows 10

**Comment by ShammyLevva** [comment]
FIxed in v7.2.1.0
